### ISSUE TITLE
Use of uniform distributions

### ISSUE THREAD

**Issue by seabbs** [martyn1fyles/HouseholdContactTracing#3]
In your code I see quite a few uses of uniform distributions to inform sensitivity analyses. Can I just confirm these are priors rather than just being sampled from? 

It seems unlikely that the best evidence for the values of all of these parameters is uniform (as that obviously implies equally lilkelihood within the distribution and then a sharp cut-off at the boundaries). My concern with that is it would place more weight than might be expected on extreme parameter combinations? 

Feel very free to just disagree and close this 😄 

Example here (and all others in this folder): 

https://github.com/martyn1fyles/HouseholdContactTracing/blob/master/SimulationScripts/growth%20rate%20scenario%20E.py

**Comment by martyn1fyles** [comment]
Hi, you're right that the uniform distributions have a strange interpretation as priors. To be honest, at the time of choosing those distributions we did not really have any good idea of what the parameters should be, so we opted to sample from a plausible range in order to explore the effects on the model, in the more recent model iterations we've switched to running the model over a hypergrid of parameters.

Our results were more focused on the different strategies and sensitivity of parameters, and trying to give a range of outcomes for a range of input parameters. Deciding what parameters should be gets very tricky in contact tracing, what with all the behavioral aspects.

**Comment by seabbs** [comment]
Sounds great but they also have a fairly strange interpretation when used in a sampling grid (as they don't represent your best guess correctly usually) as done here and described in that extreme value combinations are much more likely than people reading the analysis would expect. Great you've moved on from this.
